# Generated by Django 5.0.4 on 2024-06-06 02:05

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimg_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='imgField',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_to),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='imgBase',
            field=models.BinaryField(blank=True),
        ),
    ]
