# Generated by Django 5.0.4 on 2024-06-12 04:08

import store.models
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimg_imgfield_alter_productimg_imgbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='imgField',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_to, validators=[store.validators.validate_max_size]),
        ),
    ]
